mozilla/django-csp

- docs/configuration.rst
- docs/decorators.rst
- docs/installation.rst
I noticed a few broken links on [Read the Docs](http://django-csp.readthedocs.org/en/latest/index.html). This pull request fixes it (at least locally when building with Sphinx).
> Fix some of the interlinks in the docs.

- csp/middleware.py
- csp/tests/test_middleware.py
- docs/configuration.rst
Once https://github.com/django/django/pull/5567/ lands Django admin will support django-csp out of the box
> Django admin doesn't use inline JS anymore

- csp/decorators.py
- csp/tests/test_decorators.py
- docs/decorators.rst
The bug was causing this code:
@csp(IMG_SRC='imgsrv2.com')
def view(request):
to emit headers like `Content-Security-Policy: img-src i m g s r v 2 . c o m`
I fixed the bug, and I changed the documentation to instruct users to use lists or tuples for consistency
with the configuration.
> Fix bug when @csp arguments were strings

- csp/tests/test_decorators.py
- csp/tests/test_middleware.py
- csp/utils.py
The decorators would accidentally mutate config, causing future requests against other views to return the wrong policy.
This fixes that, and it includes tests. This builds upon code in pull request #51 , so merging this will merge both.
> Accidental config mutating bug

- .travis.yml
- csp/middleware.py
- tox.ini
This PR does two things:
- It adds django 1.10 to the build environment for python 2.7, 3.4, 3.5, and pypy
- It uses the [django.utils.deprecation.MiddlewareMixin](https://docs.djangoproject.com/en/1.10/topics/http/middleware/#django.utils.deprecation.MiddlewareMixin) to make the `CSPMiddleware` compatible with the [new](https://docs.djangoproject.com/en/1.10/topics/http/middleware/) and old middleware style.
This PR will resolve #70 
Thoughts? I would love some feedback. 😄
> Add support for django 1.10

- csp/tests/test_utils.py
- csp/utils.py
- docs/configuration.rst
Adds the following CSP directives:
* manifest-src https://github.com/mozilla/django-csp/issues/60
* worker-src
* plugin-types https://github.com/mozilla/django-csp/issues/59
* require-sri-for
* upgrade-insecure-requests https://github.com/mozilla/django-csp/issues/58
* block-all-mixed-content
Is this package tracking CSP drafts, shipped CSP directives, or both?
require-sri-for, upgrade-insecure-requests, block-all-mixed-content, and the CSP 3 headers are still in draft.  There is a tiny overhead to including them, but we gain forward compatibility assuming they stay in the specs.
On the other hand, referrer-policy https://github.com/mozilla/django-csp/issues/57 and reflected-xss were removed from CSP, but adding them could still benefit users at the cost of some historical baggage.
> Add missing directives

- docs/configuration.rst
`CSP_UPGRADE_INSECURE_REQUESTS` is used while it is supposed to be `CSP_BLOCK_ALL_MIXED_CONTENT`
> update docs with correct settings title

- CHANGES
- csp/tests/test_utils.py
- csp/utils.py
refs: #80
Using the stdlib `warnings.catch_warnings` was timing out and `pytest.deprecated_call` gave me `AssertionError: <type 'exceptions.DeprecationWarning'> did not produce DeprecationWarning`.
> add deprecation warning for child-src

- .travis.yml
- setup.py
- tox.ini
Django 1.11 has been released, so it's time to support it!
> Add support for Django 1.11 and Python 3.6

- setup.py
Django's backwards compatibility and deprecation policies mean that any future compatibility issues will be known well in advance of any breakage. There is no advantage to pinning the upper bound on the supported Django version. It means a django-csp release is required to support each version of Django (and we're currently waiting on a django-csp release to upgrade to Django 1.11).
> Remove upper bound on Django version

- csp/middleware.py
- csp/tests/settings.py
- csp/tests/test_middleware.py
- csp/tests/test_utils.py
- csp/utils.py
RE: https://github.com/mozilla/django-csp/issues/48
Add the groundwork for nonce generation to `build_policy` and `CSPMiddleware`. If the interest still primarily lies in a new template tag I would be glad to add that (as well as a simple context processor) in a follow-up PR.
Also of note: my initial pass of the nonce generation function was something like `b64encode(os.urandom(16))` and I won't push back if someone would prefer something more specific, but it seemed easier to lean on the django crypto utils.
> Add basic nonce implementation to build_policy and CSPMiddleware

- csp/tests/test_decorators.py
- csp/utils.py
In mozilla/normandy#604 we need to allow framing by any origin for only a particular view in our app. The only way we can do this (as far I've found) is to remove the `frame-ancestors` directive completely. We also want to have this directive set by default.
The current version of `@csp_replace` can't do this, because any value that would remove the directive is falsey, and `@csp_replace` doesn't allow falsey values to replace defaults. I think this is an oversight.
The code in this PR fixes this by accepting any values from `@csp_replace`, even falsey ones.
> Allow removing directives using @csp_replace

- csp/context_processors.py
- csp/tests/test_context_processors.py
Based on the open PR https://github.com/mozilla/django-csp/pull/75 - The real diff here (assuming #75 gets merged) is just the addition of `context_processors.py`
> Create context processor for CSP nonce

- .travis.yml
- CHANGES
- setup.py
- tox.ini
This also adds changelog entries for 3.3 and upcoming 3.4 releases
> Drop old django 1.6 and 1.7

- .travis.yml
- tox.ini
- Simplified tox.ini and .travis.yml configs significantly 
- Added Django 2.0-master and pypy3
> Updated travis and tox

- docs/configuration.rst
The docs seem to say that `CSP_REPORT_URI` needs to be a string, but a tuple or list works as well, since `report-uri` supports multiple URLs. This updates the docs to make that a little clearer (and follow the style of the docs for other settings).
> Correct CSP_REPORT_URI docs to mention support for a tuple or list.

- tox.ini
``--use-wheel`` was [deprecated in pip 7](https://pip.pypa.io/en/stable/news/#id25), and dropped in [pip 10](https://pip.pypa.io/en/stable/news/#b1-2018-03-31). Thanks to https://stackoverflow.com/a/50171690/10612 for the links.
> Remove --use-wheel from pip calls

- csp/extensions/__init__.py
- csp/middleware.py
- csp/templatetags/csp.py
- csp/tests/environment.py
- csp/tests/settings.py
- csp/tests/test_jinja_extension.py
- csp/tests/test_templatetags.py
- csp/tests/test_utils.py
- csp/tests/utils.py
- csp/utils.py
- docs/configuration.rst
- docs/index.rst
- docs/nonce.rst
- setup.py
First pass at a template tag based on the pr #75. This creates a `{% script %}` and {% endscript %}` token that will wrap whatever is inside with a nonce-signed script tag and prevent anything besides text nodes being expanded inside of the block. 
* This definitely needs some docs ~~and tests~~
* ~~There is also no `type` parameter in the script tag that is generated, I'm not clear on how big of a problem that is, but it should be easy enough to take a type argument~~
* ~~No Jinja support yet. Frankly, I don't know a ton about it but this could provide a good jumping off point?~~
> "Safe" script template tag

- docs/installation.rst
In Django 1.10, MIDDLEWARE replaces MIDDLEWARE_CLASSES.
> Drop obsolete MIDDLEWARE_CLASSES for MIDDLEWARE

- setup.cfg
- tox.ini
Fix tox `ERROR: unknown environment '2.7-2.1.x'` errors for Django 2.1 and a pytest deprecation warning.
> tox: add missing versions

- csp/tests/test_utils.py
- csp/utils.py
- docs/configuration.rst
Should address this issue https://github.com/mozilla/django-csp/issues/108
The PR might be a bit off, I just tried to copy the format which was used for all of the other headers. New directives are script-src-attr, script-src-elem, style-src-attr, and style-src-elem
> Add new headers used in CSP level 3 - https://w3c.github.io/webappsec-csp/

- csp/tests/test_utils.py
- csp/utils.py
- docs/configuration.rst
Also typo fix FRAME_ANCESTOR doc, and order utils.py directives in the same way that the CSP level 3 docs orders them. I was going to reoder the docs and the tests in the same way, but then I got lazy. Sorry.
> Add prefetch-src, navigate-to level 3directives

- README.rst
pypi version badge seems busted, this fixes it.
before:
after:
(visible at: https://github.com/asherf/django-csp/blob/fix-badge/README.rst)
> Fix pypi version badge

- docs/nonce.rst
As noted in issue #125 the context processors actually adds a variable with the name `CSP_NONCE` to the context.
> Fix #125: Document correct context variable name

- csp/tests/test_utils.py
- csp/utils.py
- docs/configuration.rst
- docs/index.rst
- docs/trusted_types.rst
> Added support and documentation for Trusted Types

- docs/nonce.rst
I did not test this, but I assume the Django templatetag and Jinja2 extension include the actual script code in the output.
> Add expected script to output

- setup.py
This PR adds a `project_urls` section to setup.py that will make important links appear on the left hand side of pypi for docs, changelog, bug tracking, and source code.
Here's an example of how it looks on the attrs project:
More details about `project_urls`: https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls
> add project_urls to setup.py

- CHANGES
- README.rst
- setup.py
Changes:
* rename the default branch to `main` (we might need to update RTD config)
> rename default branch

- CHANGES
- csp/tests/test_jinja_extension.py
- csp/tests/test_templatetags.py
- csp/tests/utils.py
- csp/utils.py
- docs/nonce.rst
Rebased #161 with a few updates
Overall changes:
* update the template tag unwrap regex to capture open and close brackets (from #161 was originally in #155)
* compile the script tag capturing regex
* print the non-equal templates from the `assert_template_eq` test helper
* update docs
> fix unwrap script re

- docs/configuration.rst
* Change formatting and some wording for readability sake
* Make defaults reflect the actual default values
> Tweak configuration docs

- docs/nonce.rst
> GH-182 Update docs to clarify when nonce will not be added to headers

- docs/decorators.rst
The doc does not indicate csp_replace with value of None will not include the corresponding key in the csp. I didn't know this behavior existed, wrote a decorator for delete and found the behavior i wanted already exists in the test for csp_replace.
> updating csp_replace decorator doc

- docs/contributing.rst
`pip install -e .[tests]` fails with `.tests is not a valid editable requirement`
> Wrap the test install with quotes.

- .readthedocs.yaml
- docs/conf.py
...as part of debugging why the RTD pages are not currently building
> Add readthedocs config and slightly update Sphinx config

- docs/configuration.rst
There are some settings that `django-csp` still supports, but which appear to be deprecated (comparing with MDN's docs on CSP). This changeset moves those settings 'downpage' and links to the MDN docs, which include and explain the deprecation of the CSP feature. 
Note that the settings still live in the codebase, at least for now.
This changeset sorts all of the 3.8-related parts of #197
> Update settings documentation to move deprecated-within-csp settings to their own section, at the bottom

- csp/middleware.py
it was added in django 2.0a1 https://github.com/django/django/commit/cecc079168e8669138728d31611ff3a1e7eb3a9f
> MiddlewareMixin is always present in django>=3.2

- CHANGES
- csp/decorators.py
- csp/extensions/__init__.py
- csp/middleware.py
- csp/templatetags/csp.py
- csp/tests/test_utils.py
- csp/tests/utils.py
- csp/utils.py
- docs/conf.py
- setup.py
This changeset tweaks some things flagged (and auto-fixed) by pyupgrade, targetting 3.12. Tox confirms things still work all the back back to 3.8
(Note: we still need to/should follow up with an actual close-up code review of it all, too. `django-upgrade` didn't spot anything that needed fixing, which kind of surprised me)
> Bring codebase up to modern Python using pyupgrade

- .coveragerc
- .gitignore
- CHANGES
- csp/apps.py
- csp/checks.py
- csp/constants.py
- csp/contrib/rate_limiting.py
- csp/decorators.py
- csp/middleware.py
- csp/tests/settings.py
- csp/tests/test_checks.py
- csp/tests/test_contrib.py
- csp/tests/test_decorators.py
- csp/tests/test_middleware.py
- csp/tests/test_utils.py
- csp/utils.py
- docs/configuration.rst
- docs/contributing.rst
- docs/decorators.rst
- docs/index.rst
- docs/installation.rst
- docs/migration-guide.rst
- docs/nonce.rst
- docs/reports.rst
- docs/trusted_types.rst
- tox.ini
This PR introduces a significant update to the django-csp project, focusing on enhancing the coherence between configuration and headers, and aligning with Django's common practices for settings. The CSP settings have been restructured, consolidating them into two primary options for enforced and report-only policies.
* **Consolidation of Settings**: Simplified the settings config by transitioning to a two-setting approach:
* `CONTENT_SECURITY_POLICY`: settings for the enforced policy.
* `CONTENT_SECURITY_POLICY_REPORT_ONLY`: settings for the report-only policy.
_**This is a backwards-incompatible change**_.
While this change may require refactoring for existing users...
* it consolidates and simplifies django-csp configuration,
* it ties the CSP configuration more closely with the CSP …
> Restructure CSP Configuration with Streamlined Settings (backwards incompatible)

- csp/constants.py
- csp/tests/test_middleware.py
- csp/tests/test_utils.py
- csp/utils.py
- docs/configuration.rst
- docs/contributing.rst
- docs/decorators.rst
This helps avoid potential errors introduced by incorrectly quoting CSP keywords.
> Add constants for CSP keywords

- CHANGES.md
- csp/apps.py
- csp/checks.py
- csp/constants.py
- csp/context_processors.py
- csp/contrib/rate_limiting.py
- csp/decorators.py
- csp/extensions/__init__.py
- csp/middleware.py
- csp/templatetags/csp.py
- csp/tests/environment.py
- csp/tests/test_checks.py
- csp/tests/test_constants.py
- csp/tests/test_context_processors.py
- csp/tests/test_contrib.py
- csp/tests/test_decorators.py
- csp/tests/test_jinja_extension.py
- csp/tests/test_middleware.py
- csp/tests/test_templatetags.py
- csp/tests/test_utils.py
- csp/tests/utils.py
- csp/utils.py
- docs/conf.py
- docs/contributing.rst
- pyproject.toml
- tox.ini
This add `mypy` to the test matrix, and type hints to all the code, fixing #198. `mypy` required some code changes, and I've rebased them out into separate commits, which could be added before the big one that hints all the functions.
I've built on top of PR #227, which fixes configuration issues with `tox.ini`. In that PR, I disabled `pypy` testing against Django 3.2, which was consistently breaking. I thought these changes fixed that, but they still fail 1 out of 10 times locally, so I'm keeping them disabled.
To run `mypy` locally:
```
pip install -e .[tests,typing]
```
> Add type hints, fix mypy issues (#198)

- csp/middleware.py
The usage of [`all`](https://docs.python.org/3.10/library/functions.html#all) is an overengineering of what can be handled with a simple sequence of `and`.
Also since `all` is a function which requires an iterable as the only argument it is much slower than a simple logical operator.
> Use simple logical operator in middleware

- csp/contrib/rate_limiting.py
- csp/tests/test_contrib.py
This also updates the RateLimited CSPMiddleware to remove both `report-uri` and `report-to` directives based on report percentage.
> Fix #231: report percentage of 100% should always report

- csp/contrib/rate_limiting.py
- csp/middleware.py
- csp/utils.py
- docs/migration-guide.rst
The current implementation of `csp.middleware.CSPMiddleware` doesn't lend itself to extending the functionality of it or the `csp.contrib.rate_limiting.RateLimitedCSPMiddleware` without copy/pasting the implementation of `.build_policy()` and `.build_policy_ro()`
This is a bit of an issue, because it means any updates to the base implementation of the superclass has to be manually copied into any subclasses.
For example, for my multi-tenant webapp project, we use the `RateLimitedCSPMiddleware` and have an additional requirement to generate a CSP that contains some per-tenant configuration. So I've created a custom middleware by copying the code from `RateLimitedCSPMiddleware` and adding my extra logic in.
This isn't great because if the implementation of `RateLimitedCSPMiddleware` …
> refactor(middleware): Refactor internals of CSPMiddleware so that it's easier to extend existing logic without copy/pasting it into subclass

- docs/trusted_types.rst
Fixes broken links to MDN compatibility table and W3C draft specs.
> docs: Fix trusted_types links

- csp/apps.py
- csp/checks.py
- csp/tests/test_checks.py
Check that EXCLUDE_URL_PREFIXES in settings is not a string.
If it is a string it can lead to a security issue where the string is treated as a list of characters, resulting in '/' matching all paths excluding the CSP header from all responses.
> Fix #249: Add `EXCLUDE_URL_PREFIXES` check

- csp/tests/test_middleware.py
- csp/tests/test_templatetags.py
- csp/tests/test_utils.py
- csp/utils.py
- Fixes several exceptions that'd be thrown when trying to use Python sets as config values, rather than tuples or lists. 
- Removes duplicate values from directives when building the full CSP header.
> fix: support CSP configuration as sets

- docs/conf.py
- docs/configuration.rst
- docs/index.rst
Resolves #232
(also removes some empty links from toc boilerplate & updates copyright to strftime placeholder)
Preview: https://janbrasna.github.io/django-csp/configuration.html#policy-settings
> docs: Note that reporting percentage needs rate limiting middleware

- .pre-commit-config.yaml
- csp/constants.py
- csp/utils.py
- pyproject.toml
- tox.ini
This mainly updates the tox matrix to drop Python < 3.12 for Django main branch which shifted to Django 6.0 development.
> Update project details

- csp/middleware.py
- csp/tests/test_middleware.py
- docs/installation.rst
- docs/nonce.rst
If the nonce was generated before the CSP headers were set, then allow reading it with ``request.csp_nonce``.
If the CSP headers were set with no nonce, then continue raising ``CSPNonceError`` when reading it as a string. If read as a boolean (`if request.csp_nonce`), then return `False`.
This will allow other middleware like [django-debug-toolbar](https://github.com/django-commons/django-debug-toolbar) to alter the response after the CSP middleware runs, fixing #268.
> Allow reading nonce if it was included in header

- .pre-commit-config.yaml
- CHANGES.md
- pyproject.toml
* Reformat with `pyproject-fmt v2.5.0`, and update to latest `v2.5.1`
* Add release notes, mark `request.csp_nonce` truthiness as backwards-incompatible change
* Bump version to `4.0b5`
> Prepare for 4.0b5 Release

- csp/middleware.py
- csp/tests/test_middleware.py
Further fix for issue #268 - `CSPMiddlewareAlwaysGenerateNonce` needs to read `self.csp_nonce` as a string in order to properly initialize the lazy object.
> Fix CSPMiddlewareAlwaysGenerateNonce

- docs/configuration.rst
Fixes #259
Support added in [#228@`abf8c1b`](https://github.com/mozilla/django-csp/pull/228/commits/abf8c1bd743c2f81669f84bd763e697fe2438cc1)
> docs: Update `EXCLUDE_URL_PREFIXES` configuration details
